global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'citasalud-backend-render'
    metrics_path: /actuator/prometheus
    scheme: https
    static_configs:
      - targets: ['citasalud-backend-1.onrender.com']
